<?php
require_once __DIR__ . '/../includes/auth-check.php';
require_once __DIR__ . '/../config/db.php';

// Validate trip_id
$trip_id = isset($_GET['trip_id']) ? (int)$_GET['trip_id'] : 0;
if (!$trip_id) {
    header('Location: my-trips.php');
    exit;
}

// Verify ownership and fetch trip
$stmt = getPDO()->prepare("SELECT id, name, start_date, end_date FROM trips WHERE id = ? AND user_id = ?");
$stmt->execute([$trip_id, $_SESSION['user_id']]);
$trip = $stmt->fetch();
if (!$trip) {
    header('Location: my-trips.php');
    exit;
}

$currentPage = 'calendar';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($trip['name']) ?> — Calendar — JourneyHub</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/JourneyHub/assets/css/style.css">
    <link rel="stylesheet" href="/JourneyHub/assets/css/calendar.css">
</head>
<body>
    <?php require_once __DIR__ . '/../includes/navbar.php'; ?>

    <main class="calendar-main">
        <div class="calendar-header">
            <h1>Trip Calendar — <?= htmlspecialchars($trip['name']) ?></h1>
            <div class="nav-links">
                <a href="itinerary.php?trip_id=<?= $trip_id ?>" class="nav-link">← Itinerary</a>
                <a href="budget.php?trip_id=<?= $trip_id ?>" class="nav-link">💰 Budget</a>
            </div>
        </div>

        <div class="calendar-layout">
            <!-- Calendar Grid -->
            <div class="calendar-panel">
                <div class="calendar-header-controls">
                    <button class="btn btn-secondary" id="prev-month">‹</button>
                    <h2 id="current-month">Loading...</h2>
                    <button class="btn btn-secondary" id="next-month">›</button>
                </div>
                
                <div class="calendar-grid" id="calendar-grid">
                    <!-- Generated by JavaScript -->
                </div>
            </div>

            <!-- Day Details -->
            <div class="day-details-panel">
                <h3 id="selected-date">Select a date</h3>
                <div class="activities-list" id="activities-list">
                    <p class="no-selection">Click on a date to see activities</p>
                </div>
            </div>
        </div>
    </main>

    <script>
        const TRIP_ID = <?= $trip['id'] ?>;
        const TRIP_START = "<?= $trip['start_date'] ?>";
        const TRIP_END = "<?= $trip['end_date'] ?>";
    </script>
    <script src="/JourneyHub/assets/js/calendar.js"></script>
</body>
</html>